<?php
	$connection = mysqli_connect("localhost","root","");
	$db = mysqli_select_db($connection,"sms.sql");
	$query = " UPDATE `academic_performance` SET `sem1_ia1`='$_POST[sem1_ia1]',`sem1_ia2`='$_POST[sem1_ia2]',`sem1_prelim1`='$_POST[sem1_prelim1]',`sem1_endSemExam`='$_POST[sem1_endSemExam]',`sem1_ia1_remark`='$_POST[sem1_ia1_remark]',`sem1_ia2_remark`='$_POST[sem1_ia2_remark]',`sem1_prelim_remark`='$_POST[sem1_prelim_remark]',`sem1_end_sem_remark`='$_POST[sem1_end_sem_remark]',`sem2_ia1`='$_POST[sem2_ia1]',`sem2_ia2`='$_POST[sem2_ia2]',`sem2_prelim2`='$_POST[sem2_prelim2]',`sem2_endSemExam`='$_POST[sem2_endSemExam]',`sem2_ia1_remark`='$_POST[sem2_ia1_remark]',`sem2_ia2_remark`='$_POST[sem2_ia2_remark]',`sem2_prelim_remark`='$_POST[sem2_prelim_remark]',`sem2_end_sem_remark`='$_POST[sem2_end_sem_remark]',`sem3_ia1`='$_POST[sem3_ia1]',`sem3_ia2`='$_POST[sem3_ia2]',`sem3_prelim3`='$_POST[sem3_prelim3]',`sem3_endSemExam`='$_POST[sem3_endSemExam]',`sem3_ia1_remark`='$_POST[sem3_ia1_remark]',`sem3_ia2_remark`='$_POST[sem3_ia2_remark]',`sem3_prelim_remark`='$_POST[sem3_prelim_remark]',`sem3_end_sem_remark`='$_POST[sem3_end_sem_remark]',`sem4_ia1`='$_POST[sem4_ia1]',`sem4_ia2`='$_POST[sem4_ia2]',`sem4_prelim4`='$_POST[sem4_prelim4]',`sem4_endSemExam`='$_POST[sem4_endSemExam]',`sem4_ia1_remark`='$_POST[sem4_ia1_remark]',`sem4_ia2_remark`='$_POST[sem4_ia2_remark]',`sem4_prelim_remark`='$_POST[sem4_prelim_remark]',`sem4_end_sem_remark`='$_POST[sem4_end_sem_remark]',`sem5_ia1`='$_POST[sem5_ia1]',`sem5_ia2`='$_POST[sem5_ia2]',`sem5_prelim5`='$_POST[sem5_prelim5]',`sem5_endSemExam`='$_POST[sem5_endSemExam]',`sem5_ia1_remark`='$_POST[sem5_ia1_remark]',`sem5_ia2_remark`='$_POST[sem5_ia2_remark]',`sem5_prelim_remark`='$_POST[sem5_prelim_remark]',`sem5_end_sem_remark`='$_POST[sem5_end_sem_remark]',`sem6_ia1`='$_POST[sem6_ia1]',`sem6_ia2`='$_POST[sem6_ia2]',`sem6_prelim6`='$_POST[sem6_prelim6]',`sem6_endSemExam`='$_POST[sem6_endSemExam]',`sem6_ia1_remark`='$_POST[sem6_ia1_remark]',`sem6_ia2_remark`='$_POST[sem6_ia2_remark]',`sem6_prelim_remark`='$_POST[sem6_prelim_remark]',`sem6_end_sem_remark`='$_POST[sem6_end_sem_remark]',`sem7_ia1`='$_POST[sem7_ia1]',`sem7_ia2`='$_POST[sem7_ia2]',`sem7_prelim7`='$_POST[sem7_prelim7]',`sem7_endSemExam`='$_POST[sem7_endSemExam]',`sem7_ia1_remark`='$_POST[sem7_ia1_remark]',`sem7_ia2_remark`='$_POST[sem7_ia2_remark]',`sem7_prelim_remark`='$_POST[sem7_prelim_remark]',`sem7_end_sem_remark`='$_POST[sem7_end_sem_remark]',`sem8_ia1`='$_POST[sem8_ia1]',`sem8_ia2`='$_POST[sem8_ia2]',`sem8_prelim8`='$_POST[sem8_prelim8]',`sem8_endSemExam`='$_POST[sem8_endSemExam]',`sem8_ia1_remark`='$_POST[sem8_ia1_remark]',`sem8_ia2_remark`='$_POST[sem8_ia2_remark]',`sem8_prelim_remark`='$_POST[sem8_prelim_remark]',`sem8_end_sem_remark`='$_POST[sem8_end_sem_remark]' WHERE r_no = '$_POST[r_no]'";
	$query_run = mysqli_query($connection,$query);
?>
<script type="text/javascript">
	alert("Details edited successfully.");
	window.location.href = "Mentor_Dashboard.php";
</script>