<?php
	$connection = mysqli_connect("localhost","root","");
	$db = mysqli_select_db($connection,"sms.sql");
	$query = " UPDATE `student_attendence` SET `sem1_month1_perc`='$_POST[sem1_month1_perc]',`sem1_month1_remark`='$_POST[sem1_month1_remark]',`sem1_month2_perc`='$_POST[sem1_month2_perc]',`sem1_month2_remark`='$_POST[sem1_month2_remark]',`sem1_month3_perc`='$_POST[sem1_month3_perc]',`sem1_month3_remark`='$_POST[sem1_month3_remark]',`sem2_month1_perc`='$_POST[sem2_month1_perc]',`sem2_month1_remark`='$_POST[sem2_month1_remark]',`sem2_month2_perc`='$_POST[sem2_month2_perc]',`sem2_month2_remark`='$_POST[sem2_month2_remark]',`sem2_month3_perc`='$_POST[sem2_month3_perc]',`sem2_month3_remark`='$_POST[sem2_month3_remark]',`sem3_month1_perc`='$_POST[sem3_month1_perc]',`sem3_month1_remark`='$_POST[sem3_month1_remark]',`sem3_month2_perc`='$_POST[sem3_month2_perc]',`sem3_month2_remark`='$_POST[sem3_month2_remark]',`sem3_month3_perc`='$_POST[sem3_month3_perc]',`sem3_month3_remark`='$_POST[sem3_month3_remark]',`sem4_month1_perc`='$_POST[sem4_month1_perc]',`sem4_month1_remark`='$_POST[sem4_month1_remark]',`sem4_month2_perc`='$_POST[sem4_month2_perc]',`sem4_month2_remark`='$_POST[sem4_month2_remark]',`sem4_month3_perc`='$_POST[sem4_month3_perc]',`sem4_month3_remark`='$_POST[sem4_month3_remark]',`sem5_month1_perc`='$_POST[sem5_month1_perc]',`sem5_month1_remark`='$_POST[sem5_month1_remark]',`sem5_month2_perc`='$_POST[sem5_month2_perc]',`sem5_month2_remark`='$_POST[sem5_month2_remark]',`sem5_month3_perc`='$_POST[sem5_month3_perc]',`sem5_month3_remark`='$_POST[sem5_month3_remark]',`sem6_month1_perc`='$_POST[sem6_month1_perc]',`sem6_month1_remark`='$_POST[sem6_month1_remark]',`sem6_month2_perc`='$_POST[sem6_month2_perc]',`sem6_month2_remark`='$_POST[sem6_month2_remark]',`sem6_month3_perc`='$_POST[sem6_month3_perc]',`sem6_month3_remark`='$_POST[sem6_month3_remark]',`sem7_month1_perc`='$_POST[sem7_month1_perc]',`sem7_month1_remark`='$_POST[sem7_month1_remark]',`sem7_month2_perc`='$_POST[sem7_month2_perc]',`sem7_month2_remark`='$_POST[sem7_month2_remark]',`sem7_month3_perc`='$_POST[sem7_month3_perc]',`sem7_month3_remark`='$_POST[sem7_month3_remark]',`sem8_month1_perc`='$_POST[sem8_month1_perc]',`sem8_month1_remark`='$_POST[sem8_month1_remark]',`sem8_month2_perc`='$_POST[sem8_month2_perc]',`sem8_month2_remark`='$_POST[sem8_month2_remark]',`sem8_month3_perc`='$_POST[sem8_month3_perc]',`sem8_month3_remark`='$_POST[sem8_month3_remark]' WHERE r_no = '$_POST[r_no]'";
	$query_run = mysqli_query($connection,$query);
?>
<script type="text/javascript">
	alert("Details edited successfully.");
	window.location.href = "Mentor_Dashboard.php";
</script>